### ISSUE TITLE
Add locations by cross street

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#12]
Geopy doesn't seem to have the ability to do this but Google Maps should. Since geopy uses the Google api we can possibly use the Places api to:

1. get the ID of the streets
2. Use the location data of the streets to find the intersection.

I'll try to test this out within the week.

**Comment by TangoYankee** [comment]
As a first draft of the solution...
1) There is a front-end radio button to allow users to select a method to input a location:
   a) building number and street name
   b) two cross streets
2) The selection is sent to an if/then statement
3) The back-end chooses the source of 'address' data based on the radio selection
4) "address' is inputted into google maps request. 
5) results from google maps are recorded into location
6) Location now only holds 'address,' 'latitude,' and 'longitude'
     a) recording street number and other specific values can creat parsing issues, as google results are highly inconsistent

**Comment by mosdevly** [comment]
I think I've got our geolocation solution done. This will be implemented in a new issue for Google Client API refactoring.
