### ISSUE TITLE
Add Location model

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#14]
Time to break down the `Cleanup` model. Location data should be separated so that `Location` objects can be used independently for mapping and geolocation.

**Comment by TangoYankee** [comment]
I agree that location should handle the geo data. However, when structuring the data, we should account for the inconsistency of the results from geopy. It may not be worth the effort to store anything more than 'address', 'longitude', and 'latitude' as they are returned from geopy. Computers should only need Lat and Long to map a location. Humans should only need address to understand a location. I propose waiting for later iterations of the project to implement higher resolution breakdowns.
