### ISSUE TITLE
Time and date format

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#28]
There is no SQL slot to take AM/PM
Format is 24hr, should be 12hr
Date is yyyy-mm-dd. Users will be used to mm-dd-yyyy

**Comment by mosdevly** [comment]
This is handled automatically by  the app during serialization. I checked it as well a week ago when I saw the change. I'll double check that user inputs are causing problems when using mm-dd-yyyy but we can handle that on the back any way.

**Comment by mosdevly** [comment]
Forgot to mention: the date changes I saw last week in the templates seemed to be causing a bug. I don't remember what it was at the time, just that I removed the special formatting and the site worked without it.

**Comment by TangoYankee** [comment]
1. 12hr to 24hr functionality is in use in a few places
2. mm-dd-yyyy to yyyy-mm-dd is only hypothetical
   - Users still input as yyyy-mm-dd.

**Comment by TangoYankee** [comment]
Could you link the docs that outline SQLAlchemy's handling of date/time? My Google skills have left me wanting

**Comment by mosdevly** [comment]
Ok I checked this out this week and I was wrong, SQLAlchemy doesn't have a field to automatically do this for us. Sorry about that. What I had in mind was a model field, but it's not automatic.

That said, I think a simple utility function on the model object can solve this neatly for us. Ideally, we can just use the `Cleanup` object and type something like `Cleanup.normal_time` to get what we want. A whole file of time functions is definitely overkill.

I'll push up what I have in mind tonight and you can let me know what you think.

**Comment by TangoYankee** [comment]
Things to account for when creating a solution:
- [ ] The cleanup time data is taken from the user as two separate strings: **string one** is the *hour*. **string two** is *am* or *pm*
- [ ] These two strings must formatted to be saved together in SQL
- [ ] There are two uses to show the time to the user. Both must be preserved by the new solution
   1. Display a static time when showing a cleanup's information
   2. Create default values for inputs when editing the cleanup or submitting it to public works. 
       - this requires splitting the hour and am/pm into separate values. 

Also, if you want to get rid of input_handling.py...
- [ ] The is another live function which lives there
```
def check_participants(user, participants):
    participant_ids = []
    for participant in participants:
        participant_ids.append(participant.id)
    return user in participant_ids
```
   - This function must be moved before the file can be removed. 
   - the function *get_full_address* should be obsolete with the reversion to your google/address solution

**Comment by mosdevly** [comment]
PR #62 I didn't get rid of the whole file, just the time methods.

**Comment by TangoYankee** [comment]
I get an error when I try to input "hh:mm:pm" into the SQL database. I believe that using a frontend tool like bootstrap will clear this up.

**Comment by mosdevly** [comment]
Not currently an issue due to PR #76
