### ISSUE TITLE
Lost in the merge

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#35]
Functionality to integrate with public works and convert between 24/12hr time was lost in the the pulls.

**Comment by mosdevly** [comment]
Ok. Can you explain again here what the issue was? As I understand it you wanted to make sure that the times/dates were displayed in 12hr format on the web pages, right?

I'm reviewing this right now.

**Comment by TangoYankee** [comment]
#### Two functions translate between 12hr am/pm with 24hr time. Users input cleanup information with two variables: **hr** and **am/pm**. 
1. First  [function](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/input_handling.py): line 8
   - User views a cleanup and program pulls **24hr** time from SQL
   - Function takes **24hr** time and converts it to **12hr am/pm**
   - **12hr am/pm** time is displayed to user
2. Second [function](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/input_handling.py): line 14
    - Users [create, line 127](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/views/cleanups.py) cleanup in **12 hr am/pm**  
    - Function translates it into **24hr** time 
    - Program saves returned **24hr** time to SQL.

##### The functions still exist. However, it is not fully utilized- there are pages that still need to implement it
