### ISSUE TITLE
Cleanout repo

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#49]
lots of files currently in circuluation that we no longer need. We can remove all unused files and folders. They are maintained in the repository history if ever we need them again.

**Comment by TangoYankee** [comment]
Are you talking about the Trashtalk *repository*? Because the trashtalk *folder* seems to use all its files.

**Comment by mosdevly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dates](https://trello.com/c/sjlKLw3q/1-dates)
