### ISSUE TITLE
Configuration of Passwords and Accounts

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#51]
- [ ] Create project accounts for Trashtalk. Get them out of my name
- [ ] Configure all passwords and accounts in settings.py and dev.cfg
       - Make sure all accounts function correctly
- [ ] Hold passwords in 1password.com account

**Comment by mosdevly** [comment]
Dude we were totally on the same brain wave here!!!

I'm partial to LastPass. Works really well for projects with lots of complex login data (like databases, SSH, and plain ole passwords). Is 1password.com pretty nice to use?

**Comment by TangoYankee** [comment]
Honestly, I've never used any password service. I only know of it because it was discussed at an OpenOakland Steering Committee meeting. They are expecting one or two free years of service, for all OO projects.

**Comment by mosdevly** [comment]
I'll send out share invitations on LastPass soon. But this issue has been covered!
