### ISSUE TITLE
Google Maps Endpoint

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#52]
#### The formatting of the Google Maps Endpoint is fickle and has caused me issues for months. 
- Google wants the key at the end of the URL 
- If the key is at the end, the coordinates need to be defined in the center
- If the coordinates are defined in the center, they need to be defined using formatting
- All variables defined using formatting must be defined at the same time
- The API Key can't be defined until the coordinates are defined
😩 

#### These formatting issues break these solutions 
  - They require the coordinates to be in the API Key position:
> Recommend set the value for gmap directly or:
```
query_result = current_app.config['GOOGLE_MAPS_ENDPOINT'] + cleanups.gmap_query

# OR
query_result = "{0}{1}".format(current_app.config['GOOGLE_MAPS_ENDPOINT'], cleanups.gmap_query)

# OR 
gmap=current_app.config['GOOGLE_MAPS_ENDPOINT'] + cleanups.gmap_query
```

**Comment by mosdevly** [comment]
There may be some popular issues with the parameters or something. But this isn't *supposed* to be how it works:

https://developers.google.com/maps/documentation/embed/get-api-key

I haven't had these issues but I'll re-test it. Are you getting a particular error when you use it?

**Comment by mosdevly** [comment]
So I just took a look at the docs again. I'm not entirely sure what you're using it for after reviewing the changes on master. Correct me if I'm wrong but you want to use coordinates with the maps api?

If so, that's not possible. The Googles Maps we are using is an embed api.

https://developers.google.com/maps/documentation/embed/guide

It generally only accepts queries about places. Passing coordinates requires use of the `center` parameter. And that will simply center the map on that. It doesn't provide direction or info about the place. Just a centered image.

Our maps implementation is incomplete. That work got buried in all the maintenance and other higher priority tasks. But it's coming up. Current implementation send requests using the address the user submits. 

I'll work on this when I get the other issues out of the way. So don't make changes to the maps implementation. See #12

**Comment by howarddd** [comment]
Can we chat about this all together??   maybe sit down together and untangle assumptions??

**Comment by TangoYankee** [comment]
1. After further review, your method of calling the API works *as you already knew* 😛 
   - My error was unrelated and came from [settings.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/settings.py): 
   - In the below code, google_maps_key failed to be properly set for me
   - My previous solution did not work by addressing the Google API format. 
   - My solution only worked because it set the key in another file. This file set the key successfully.
```
GOOGLE_MAPS_KEY = os.getenv('GOOGLE_MAPS_KEY')
``` 

2. Coordinates are a valid method to view a location. 
   - Users can 'view a larger map.' This brings them to google.com/maps
   - at google.com/maps, users can get directions to the location. 
   - give this a try in [cleanups.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/views/cleanups.py) line 55
```
    coordinates = "{0},{1}".format(cleanups.location.latitude, cleanups.location.longitude)
    gmap = "{0}{1}".format(current_app.config['GOOGLE_MAPS_ENDPOINT'],
                           coordinates)
```

3. I am still concerned about inconsistent address formats that hinder parsing
   - I advocate keeping the whole address as a single variable, rather than separating it into several parts

**Comment by mosdevly** [comment]
I recommend reviewing the official docs for both Google Maps and geopy. They provide information about how we need to implement them that can help you understand the code better. I'd ask that you continue to give feedback and suggestions, as well as report bugs but please do no modify the current implementation here. I'm super strapped for time and having to redo the same code is a set back.

Address parsing is necessary. If geopy is too unreliable we can use something else, but it isn't likely to change the need to parse addresses. geopy is currently sufficient for our purposes.

As for address variables, we save all relevant data points on the `Location` model. That includes a property for the full address and coordinates (`Location.address`, `Cleanup.location.address` and `Location.coordinates`, `Cleanup.location.coordinates` respectively can be used). The model fields should model the data we receive and use.

**Comment by TangoYankee** [comment]
You're lead on this issue. I will refrain from code changes. I'll only make comments.
