### ISSUE TITLE
Division of Tasks

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#54]
I'm proposing to create a Frontend project (like the current Backend one). I hesitate to recommend we use a better tool like Trello at this stage, but I'd like to know what you think about that.

Usually teams will divide the work broadly in this way. We need to continue to reduce conflicting changes, speed up development and get more done overall so this should help us a lot.

In short, let's do these things:

1. Post issues on Github for any changes, updates and/or new features we want to work on.
2. Create very specific tasks for those things on the Project boards, like we've been doing for the most part.
3. Put our names on any tasks that we are *currently* working on. This will prevent me from working on something you're already doing and vice versa.

We can track status and progress of the issues on the Project boards. That way we both know who is working on what and we can be confident we won't duplicate effort.

**Comment by TangoYankee** [comment]
We should discuss these issues via teleconference

**Comment by TangoYankee** [comment]
Alright! Let's do this! Do you have a high priority task in mind that you want me to start on?

**Comment by mosdevly** [comment]
YUS.
So we've been talking since this but let's keep this going.

I've started putting your name on tasks that I think you wouldn't have too much trouble accomplishing. Of course, feel free to nab an unassigned task if you feel you can handle it.

Some other things I think you should continue to research:
- [ ] Vue.js: We need to start looking toward 2018 development. A frontend framework is in our future to make the site more delightful to interact with.
- [ ] Assets: Download our own versions of third-party stylesheets and javascripts that we're using.
- [ ] Assets: Optimize images in the `static/images` folder. They should have consistent file names and extension. Names should all be uncapitalized snakecase. You may be able to write a simple python script that goes through the directory and normalizes file names ('bow rake.jpg' should be bow_rake.jpg.; 'Large Broom.PNG' should be 'large_broom.png', and so forth). Images should all be proportional in dimensions and file size (nothing above 1MB)
- [ ] Assets: Again in the `static/images` folder Icons should be in the `icons/` folder, default images in `defaults/`, and app specific images in their own folder.

I think the work we need to accomplish on the frontend is LARGE. And you seem much more comfortable there. We very much need better management of our assets and we also need to start moving away from static templates, which is what Vue.js can do for us. Making the site feel a little more dynamic can encourage users to actually fill out the forms, and streamline the process for them.

**Comment by mosdevly** [comment]
@TangoYankee I did some research yesterday on where we could reasonably head with design in 2018. I want to know if you've seen some things you want to implement to make Trashtalk visually appealing and super simple to work with.

My thoughts: 
- We can implement Javascript with jQuery soon to completely separate backend and frontend. 
- Due to above, turn the Django app into an API that serves the data.

There's heavy duty frameworks like Angular and React that are worth looking at but they seem like overkill at this stage.
