### ISSUE TITLE
Exception handling for Geopy and Google Maps

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#56]
Lots of blank except statements in the code. Not helping us. Need to think about the exceptions that can happen in those areas and how to raise them to debug.

**Comment by howarddd** [comment]
can you show where this is....?   TIA.

**Comment by mosdevly** [comment]
Ah yes, where we see this kind of code:

```
try:
    # some code
except:
    # some more code
```

...we need to list the exceptions we expect, like so:
```
try:
    # some code
except (SomeException, AnotherException): 
    logger.exception("Some message to send with the raised exception")
```
Catch alls should be avoided. `try/except` clauses should name exceptions and handle them specifically. Here's some more info below, but what you can do is look at the sections of code that have these catch-alls and research what kind of errors are likely to occur there. Then list and handle the exceptions by name within the block.

https://docs.python.org/3/tutorial/errors.html#handling-exceptions

**Comment by TangoYankee** [comment]
Gotcha 😳

**Comment by TangoYankee** [comment]
This logic in [cleanups.py](https://github.com/openoakland/TrashTalk/blob/master/trashtalk/views/cleanups.py) line 136 needs to be reworked. 

```
            full_address = get_full_address(cleanup_dict)
            try:
                geoloc = get_location(full_address)
            except:
                current_app.logger.exception("There was an error finding location.")
                flash("s%: Address not found" % full_address)
                return redirect(url_for('cleanups.edit', cleanup_id=cleanup_id))
            else:
                location_dict = {"number": geoloc.address, "latitude": geoloc.latitude, "longitude": geoloc.longitude}
                cleanup_dict.pop("location",None)#Hack- location should be renamed, coming from HTML
```

**Comment by mosdevly** [comment]
No more Flask, no more task! (PR #76)
