### ISSUE TITLE
Google Cloud Billing

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#58]
Got this error while deploying the app tonight:
```
FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.
```

**Comment by TangoYankee** [comment]
Contact Howard for a location to Deploy
- Howard has a specific domain picked out
- The account for my domain is turned off. It was using credits without a projected purpose. 

Are you deploying the app in its current form?

**Comment by mosdevly** [comment]
Yeah I was just going to put it online so that Howard could demo it. I'll checkin with both of you tonight on the switch. If I have time this afternoon I'll just try to throw on heroku temporarily for demos.

**Comment by TangoYankee** [comment]
No rush for it tonight. OO is canceled for the holiday. Merry Spooksmis! 👻

**Comment by TangoYankee** [comment]
Redefining the issue as finding a server to host the site
