### ISSUE TITLE
Find a host to serve Trashtalk

### ISSUE THREAD

**Issue by TangoYankee** [openoakland/TrashTalk#63]
Gotta find a home. The requested domain is *trashtalk-oakland.org*

**Comment by mosdevly** [comment]
I'll get some price quotes on the cost that we can give to Howard so he can help us figure out how OO will pay for/reimburse us for this.

**Comment by mosdevly** [comment]
We're at heroku for now. I'll invest in a domain name and get us set up there in the new year. Done in PR #76
