### ISSUE TITLE
Frontend assets folder

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#77]
With the Django app there's a predefined structure we can follow to make life a bit easier.

Basic site images like default avatars and default clean up icons and many other similar items should be stored in `trashtalk/trashtalk/static/images`.

Stylesheets should be stored in `trashtalk/trashtalk/static/stylesheets`.

Any custom javascripts should be stored in `trashtalk/trashtalk/static/scripts`

**Comment by TangoYankee** [comment]
Still reviewing the supporting docs to figure out this puzzle

**Comment by mosdevly** [comment]
Django will definitely seem a little un-intuitive at first. Especially when you're  a little new to Python :) I also should clarify the directories I'm referring too. I just realized how ambiguous that is.

Pull the latest code for updates first. Much has changed.

The official documentation is a very, very fine resource. It will explain every little aspect. But it's worth giving a basic summary here of how it works.

Our app structure:
```
trashtalk (project root)
|-- trashtalk/  (project directory)
     |-- apps/
     |-- static/ (all static assets)
|-- manage.py
```
- The application is always defined in relation to `manage.py`. In our case, trashtalk root is the `PROJECT_ROOT` or you may see it called `DJANGO_ROOT`
- Our app expects all static assets (css, js, images, etc) to be located in `static/`. We set this up in our `common.py`
- During local development, django will server static assets.
- When the site is deployed live, we use `whitenoise` package to serve static assets. 
- All links on the templates to our assets can be accessed by calling: `{% static 'path/to/stylesheet.css' %}`

Eventually  we might use a CDN to store them, but the point is that django *does not* manage them in a live server environment. Instead, the app uses the `collectstatic` command to process all the assets to the cdn for us. 

This is why every asset needs to be in that folder. Otherwise django will never find them.

Also it's extremely bad to 'hotlink'. This is where we link to images stored on another site directly from our page. All images need to be served from our static assets.

**Comment by mosdevly** [comment]
Completed in PR #85
