### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#91]
- [x] Staticfiles manifest isn't compressing js files (and probably css too) which means sticking with CDNs
https://papertrailapp.com/systems/trashtalkdev/events?focus=874158431215951881&selected=874158431215951881
`ValueError: Missing staticfiles manifest entry for 'scripts/jquery.min.js'`

- [x] Manually upload assets in the meantime
- [ ] Implement custom `CustomFileHandler` class for auto-creating logs folders

**Comment by TangoYankee** [comment]
Ahh, drats. I have the CDN addresses in another branch. I'll add swap them
back and push an update now. Also, how do i create a table in postgres?
There are options for stacks and servers and all these fancy things. I just
want to make a humble trashtalk table.

**Comment by mosdevly** [comment]
I found a good workaround so no worries. Your CDN links are fine but your original implementation was correct. It's just that the assets folders weren't all being created (only some). Still haven't figured out why but we're live again.
