### ISSUE TITLE
Cleanup Styling Bugs

### ISSUE THREAD

**Issue by mosdevly** [openoakland/TrashTalk#98]
It may just be my browser but the All Cleanups page wasn't displaying right. Something had gone wrong with the `list-group` CSS class. I ended up just commenting-out the parts so I could get a reasonable display.

@TangoYankee can you take a look?

- [ ] All cleanups list-grouping
- [ ] Show cleanup links at the bottom are clipped by the footer

**Comment by TangoYankee** [comment]
1. I'm uncertain about your original concern. There isn't a dedicated "show cleanup" link anymore. The entire row is meant to be a clickable link. I'll submit my solution. Let me know if you still have issues and would like a redesign.  

2. I can see a concern that the footer clips the cleanup links. However, the footer is designed to be in a fixed position. Users can scroll if they need to access a link that temporarily falls behind it. If this becomes a significant issue, my first step would be to redesign the footer.
